//
//  EFIconFontTypicons.swift
//  EFIconFont
//
//  Created by EyreFree on 2019/3/20.
//
//  Copyright (c) 2019 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation

public extension EFIconFont {

    public static let typicons = EFIconFontTypicons.self
}

extension EFIconFontTypicons: EFIconFontCaseIterableProtocol {

    public static var name: String {
        return "typicons"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontTypicons: String {
    case weatherSunny = "\u{eb55}"
    case volumeMute = "\u{eb54}"
    case zoomOutline = "\u{eb53}"
    case videoOutline = "\u{eb52}"
    case weatherShower = "\u{eb51}"
    case zoomIn = "\u{eb50}"
    case userDelete = "\u{eb4f}"
    case wiFiOutline = "\u{eb4e}"
    case volumeUp = "\u{eb4d}"
    case video = "\u{eb4c}"
    case zoomOutOutline = "\u{eb4b}"
    case weatherDownpour = "\u{eb4a}"
    case timesOutline = "\u{eb49}"
    case userAddOutline = "\u{eb48}"
    case tree = "\u{eb47}"
    case vendorAndroid = "\u{eb46}"
    case world = "\u{eb45}"
    case worldOutline = "\u{eb44}"
    case weatherWindyCloudy = "\u{eb43}"
    case socialGithubCircular = "\u{eb42}"
    case thSmall = "\u{eb41}"
    case vendorApple = "\u{eb40}"
    case times = "\u{eb3f}"
    case thMenuOutline = "\u{eb3e}"
    case uploadOutline = "\u{eb3d}"
    case zoom = "\u{eb3c}"
    case weatherSnow = "\u{eb3b}"
    case wavesOutline = "\u{eb3a}"
    case tick = "\u{eb39}"
    case zoomOut = "\u{eb38}"
    case thMenu = "\u{eb37}"
    case wiFi = "\u{eb36}"
    case zoomInOutline = "\u{eb35}"
    case thLarge = "\u{eb34}"
    case wine = "\u{eb33}"
    case warningOutline = "\u{eb32}"
    case weatherWindy = "\u{eb31}"
    case starburstOutline = "\u{eb30}"
    case weatherNight = "\u{eb2f}"
    case socialSkypeOutline = "\u{eb2e}"
    case stopwatch = "\u{eb2d}"
    case starHalfOutline = "\u{eb2c}"
    case star = "\u{eb2b}"
    case weatherStormy = "\u{eb2a}"
    case weatherPartlySunny = "\u{eb29}"
    case waves = "\u{eb28}"
    case thumbsOk = "\u{eb27}"
    case weatherCloudy = "\u{eb26}"
    case socialTumbler = "\u{eb25}"
    case warning = "\u{eb24}"
    case watch = "\u{eb23}"
    case userOutline = "\u{eb22}"
    case volume = "\u{eb21}"
    case volumeDown = "\u{eb20}"
    case userAdd = "\u{eb1f}"
    case tag = "\u{eb1e}"
    case ticket = "\u{eb1d}"
    case vendorMicrosoft = "\u{eb1c}"
    case userDeleteOutline = "\u{eb1b}"
    case upload = "\u{eb1a}"
    case user = "\u{eb19}"
    case sortNumericallyOutline = "\u{eb18}"
    case thermometer = "\u{eb17}"
    case thumbsUp = "\u{eb16}"
    case spanner = "\u{eb15}"
    case trash = "\u{eb14}"
    case thListOutline = "\u{eb13}"
    case tickOutline = "\u{eb12}"
    case time = "\u{eb11}"
    case thumbsDown = "\u{eb10}"
    case support = "\u{eb0f}"
    case socialLastFmCircular = "\u{eb0e}"
    case thList = "\u{eb0d}"
    case thSmallOutline = "\u{eb0c}"
    case tags = "\u{eb0b}"
    case starFullOutline = "\u{eb0a}"
    case socialVimeo = "\u{eb09}"
    case sortNumerically = "\u{eb08}"
    case spiral = "\u{eb07}"
    case thLargeOutline = "\u{eb06}"
    case socialYoutubeCircular = "\u{eb05}"
    case socialYoutube = "\u{eb04}"
    case starburst = "\u{eb03}"
    case tabsOutline = "\u{eb02}"
    case socialDribbbleCircular = "\u{eb01}"
    case socialVimeoCircular = "\u{eb00}"
    case starHalf = "\u{eaff}"
    case socialSkype = "\u{eafe}"
    case spannerOutline = "\u{eafd}"
    case sortAlphabeticallyOutline = "\u{eafc}"
    case socialPinterestCircular = "\u{eafb}"
    case starOutline = "\u{eafa}"
    case shoppingCart = "\u{eaf9}"
    case socialFacebook = "\u{eaf8}"
    case socialTwitterCircular = "\u{eaf7}"
    case socialLastFm = "\u{eaf6}"
    case scissorsOutline = "\u{eaf5}"
    case sortAlphabetically = "\u{eaf4}"
    case refreshOutline = "\u{eaf3}"
    case socialTwitter = "\u{eaf2}"
    case socialLinkedin = "\u{eaf1}"
    case socialTumblerCircular = "\u{eaf0}"
    case socialPinterest = "\u{eaef}"
    case socialGithub = "\u{eaee}"
    case socialLinkedinCircular = "\u{eaed}"
    case socialGooglePlus = "\u{eaec}"
    case socialInstagramCircular = "\u{eaeb}"
    case socialInstagram = "\u{eaea}"
    case socialGooglePlusCircular = "\u{eae9}"
    case socialDribbble = "\u{eae8}"
    case shoppingBag = "\u{eae7}"
    case socialFlickr = "\u{eae6}"
    case pointOfInterestOutline = "\u{eae5}"
    case plusOutline = "\u{eae4}"
    case socialFlickrCircular = "\u{eae3}"
    case scissors = "\u{eae2}"
    case socialFacebookCircular = "\u{eae1}"
    case socialAtCircular = "\u{eae0}"
    case mediaPlay = "\u{eadf}"
    case radarOutline = "\u{eade}"
    case pipette = "\u{eadd}"
    case lockOpenOutline = "\u{eadc}"
    case planeOutline = "\u{eadb}"
    case printer = "\u{eada}"
    case refresh = "\u{ead9}"
    case rssOutline = "\u{ead8}"
    case rss = "\u{ead7}"
    case puzzle = "\u{ead6}"
    case puzzleOutline = "\u{ead5}"
    case radar = "\u{ead4}"
    case pinOutline = "\u{ead3}"
    case pointOfInterest = "\u{ead2}"
    case power = "\u{ead1}"
    case plug = "\u{ead0}"
    case powerOutline = "\u{eacf}"
    case plane = "\u{eace}"
    case plus = "\u{eacd}"
    case phoneOutline = "\u{eacc}"
    case pen = "\u{eacb}"
    case locationArrowOutline = "\u{eaca}"
    case pi = "\u{eac9}"
    case infinity = "\u{eac8}"
    case phone = "\u{eac7}"
    case piOutline = "\u{eac6}"
    case mediaEjectOutline = "\u{eac5}"
    case pencil = "\u{eac4}"
    case pin = "\u{eac3}"
    case microphone = "\u{eac2}"
    case minusOutline = "\u{eac1}"
    case notes = "\u{eac0}"
    case news = "\u{eabf}"
    case messages = "\u{eabe}"
    case mortarBoard = "\u{eabd}"
    case message = "\u{eabc}"
    case notesOutline = "\u{eabb}"
    case infoLarge = "\u{eaba}"
    case mediaPause = "\u{eab9}"
    case group = "\u{eab8}"
    case microphoneOutline = "\u{eab7}"
    case minus = "\u{eab6}"
    case mediaStop = "\u{eab5}"
    case mediaRewindOutline = "\u{eab4}"
    case mediaRecord = "\u{eab3}"
    case mediaStopOutline = "\u{eab2}"
    case mediaPlayOutline = "\u{eab1}"
    case mediaFastForwardOutline = "\u{eab0}"
    case mediaPlayReverse = "\u{eaaf}"
    case linkOutline = "\u{eaae}"
    case messageTyping = "\u{eaad}"
    case mediaRewind = "\u{eaac}"
    case mediaPlayReverseOutline = "\u{eaab}"
    case mediaRecordOutline = "\u{eaaa}"
    case mediaFastForward = "\u{eaa9}"
    case location = "\u{eaa8}"
    case mediaPauseOutline = "\u{eaa7}"
    case lightbulb = "\u{eaa6}"
    case lockOpen = "\u{eaa5}"
    case map = "\u{eaa4}"
    case infinityOutline = "\u{eaa3}"
    case lockClosed = "\u{eaa2}"
    case mail = "\u{eaa1}"
    case locationOutline = "\u{eaa0}"
    case lockClosedOutline = "\u{ea9f}"
    case mediaEject = "\u{ea9e}"
    case flowChildren = "\u{ea9d}"
    case key = "\u{ea9c}"
    case leaf = "\u{ea9b}"
    case locationArrow = "\u{ea9a}"
    case link = "\u{ea99}"
    case keyboard = "\u{ea98}"
    case inputChecked = "\u{ea97}"
    case keyOutline = "\u{ea96}"
    case inputCheckedOutline = "\u{ea95}"
    case infoOutline = "\u{ea94}"
    case infoLargeOutline = "\u{ea93}"
    case heartFullOutline = "\u{ea92}"
    case info = "\u{ea91}"
    case groupOutline = "\u{ea90}"
    case imageOutline = "\u{ea8f}"
    case image = "\u{ea8e}"
    case html5 = "\u{ea8d}"
    case heart = "\u{ea8c}"
    case headphones = "\u{ea8b}"
    case heartHalfOutline = "\u{ea8a}"
    case gift = "\u{ea89}"
    case home = "\u{ea88}"
    case homeOutline = "\u{ea87}"
    case heartOutline = "\u{ea86}"
    case globeOutline = "\u{ea85}"
    case folderDelete = "\u{ea84}"
    case feather = "\u{ea83}"
    case flowParallel = "\u{ea82}"
    case flowSwitch = "\u{ea81}"
    case globe = "\u{ea80}"
    case folderOpen = "\u{ea7f}"
    case flowMerge = "\u{ea7e}"
    case folderAdd = "\u{ea7d}"
    case folder = "\u{ea7c}"
    case film = "\u{ea7b}"
    case flash = "\u{ea7a}"
    case flagOutline = "\u{ea79}"
    case flashOutline = "\u{ea78}"
    case flag = "\u{ea77}"
    case edit = "\u{ea76}"
    case download = "\u{ea75}"
    case filter = "\u{ea74}"
    case ejectOutline = "\u{ea73}"
    case eye = "\u{ea72}"
    case eyeOutline = "\u{ea71}"
    case downloadOutline = "\u{ea70}"
    case equalsOutline = "\u{ea6f}"
    case exportOutline = "\u{ea6e}"
    case export = "\u{ea6d}"
    case eject = "\u{ea6c}"
    case equals = "\u{ea6b}"
    case dropbox = "\u{ea6a}"
    case deviceTablet = "\u{ea69}"
    case deviceDesktop = "\u{ea68}"
    case divide = "\u{ea67}"
    case documentDelete = "\u{ea66}"
    case devicePhone = "\u{ea65}"
    case documentText = "\u{ea64}"
    case chartPieOutline = "\u{ea63}"
    case directions = "\u{ea62}"
    case delete = "\u{ea61}"
    case divideOutline = "\u{ea60}"
    case document = "\u{ea5f}"
    case codeOutline = "\u{ea5e}"
    case contacts = "\u{ea5d}"
    case documentAdd = "\u{ea5c}"
    case cogOutline = "\u{ea5b}"
    case compass = "\u{ea5a}"
    case cog = "\u{ea59}"
    case deviceLaptop = "\u{ea58}"
    case css3 = "\u{ea57}"
    case chartBarOutline = "\u{ea56}"
    case coffee = "\u{ea55}"
    case database = "\u{ea54}"
    case deleteOutline = "\u{ea53}"
    case chevronRight = "\u{ea52}"
    case calculator = "\u{ea51}"
    case creditCard = "\u{ea50}"
    case chevronLeft = "\u{ea4f}"
    case code = "\u{ea4e}"
    case cloudStorage = "\u{ea4d}"
    case chevronLeftOutline = "\u{ea4c}"
    case chartLine = "\u{ea4b}"
    case clipboard = "\u{ea4a}"
    case chartAreaOutline = "\u{ea49}"
    case cloudStorageOutline = "\u{ea48}"
    case chartLineOutline = "\u{ea47}"
    case chartPie = "\u{ea46}"
    case chevronRightOutline = "\u{ea45}"
    case chartBar = "\u{ea44}"
    case cancel = "\u{ea43}"
    case cameraOutline = "\u{ea42}"
    case batteryHigh = "\u{ea41}"
    case brush = "\u{ea40}"
    case arrowSyncOutline = "\u{ea3f}"
    case calendarOutline = "\u{ea3e}"
    case briefcase = "\u{ea3d}"
    case camera = "\u{ea3c}"
    case cancelOutline = "\u{ea3b}"
    case bell = "\u{ea3a}"
    case batteryMid = "\u{ea39}"
    case businessCard = "\u{ea38}"
    case calendar = "\u{ea37}"
    case attachmentOutline = "\u{ea36}"
    case book = "\u{ea35}"
    case batteryFull = "\u{ea34}"
    case chartArea = "\u{ea33}"
    case beaker = "\u{ea32}"
    case beer = "\u{ea31}"
    case arrowSync = "\u{ea30}"
    case bookmark = "\u{ea2f}"
    case arrowUpThick = "\u{ea2e}"
    case batteryLow = "\u{ea2d}"
    case batteryCharge = "\u{ea2c}"
    case at = "\u{ea2b}"
    case arrowUpOutline = "\u{ea2a}"
    case backspaceOutline = "\u{ea29}"
    case backspace = "\u{ea28}"
    case arrowRepeatOutline = "\u{ea27}"
    case attachment = "\u{ea26}"
    case arrowUnsorted = "\u{ea25}"
    case arrowShuffle = "\u{ea24}"
    case arrowUp = "\u{ea23}"
    case arrowMove = "\u{ea22}"
    case arrowRightOutline = "\u{ea21}"
    case arrowSortedDown = "\u{ea20}"
    case arrowRight = "\u{ea1f}"
    case arrowRepeat = "\u{ea1e}"
    case arrowRightThick = "\u{ea1d}"
    case arrowSortedUp = "\u{ea1c}"
    case arrowMinimiseOutline = "\u{ea1b}"
    case arrowMaximise = "\u{ea1a}"
    case arrowBack = "\u{ea19}"
    case arrowMaximiseOutline = "\u{ea18}"
    case arrowMoveOutline = "\u{ea17}"
    case arrowMinimise = "\u{ea16}"
    case arrowLeftThick = "\u{ea15}"
    case arrowLoop = "\u{ea14}"
    case arrowForwardOutline = "\u{ea13}"
    case arrowLoopOutline = "\u{ea12}"
    case arrowBackOutline = "\u{ea11}"
    case arrowDownOutline = "\u{ea10}"
    case anchorOutline = "\u{ea0f}"
    case arrowLeft = "\u{ea0e}"
    case arrowLeftOutline = "\u{ea0d}"
    case arrowForward = "\u{ea0c}"
    case archive = "\u{ea0b}"
    case arrowDownThick = "\u{ea0a}"
    case arrowDown = "\u{ea09}"
    case adjustContrast = "\u{ea08}"
    case anchor = "\u{ea07}"
    case adjustBrightness = "\u{ea06}"
}
