platform :ios, '8.0'
use_frameworks!

target 'EFIconFont_Example' do
  pod 'EFIconFont', :subspecs => ['Core', 'AntDesign', 'FontAwesome', 'Ionicons', 'Octicons'], :path => '../'

  target 'EFIconFont_Tests' do
    inherit! :search_paths

    
  end
end
