//
//  EFIconFontElusiveIcons.swift
//  EFIconFont
//
//  Created by EyreFree on 2019/3/20.
//
//  Copyright (c) 2019 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation

public extension EFIconFont {

    public static let elusiveIcons = EFIconFontElusiveIcons.self
}

extension EFIconFontElusiveIcons: EFIconFontCaseIterableProtocol {

    public static var attributes: [NSAttributedString.Key : Any] = [:]

    public var name: String {
        return "elusiveicons"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontElusiveIcons: String {
    case zoomOut = "\u{e844}"
    case volumeOff = "\u{e843}"
    case zoomIn = "\u{e842}"
    case wrench = "\u{e841}"
    case wheelchair = "\u{e840}"
    case wordpress = "\u{e83f}"
    case wrenchAlt = "\u{e83e}"
    case youtube = "\u{e83d}"
    case warningSign = "\u{e83c}"
    case w3c = "\u{e83b}"
    case website = "\u{e83a}"
    case websiteAlt = "\u{e839}"
    case volumeUp = "\u{e838}"
    case volumeDown = "\u{e837}"
    case vkontakte = "\u{e836}"
    case vimeo = "\u{e835}"
    case viewMode = "\u{e834}"
    case viadeo = "\u{e833}"
    case videoAlt = "\u{e832}"
    case video = "\u{e831}"
    case videoChat = "\u{e830}"
    case user = "\u{e82f}"
    case usd = "\u{e82e}"
    case unlock = "\u{e82d}"
    case upload = "\u{e82c}"
    case universalAccess = "\u{e82b}"
    case twitter = "\u{e82a}"
    case unlockAlt = "\u{e829}"
    case tumblr = "\u{e828}"
    case trashAlt = "\u{e827}"
    case trash = "\u{e826}"
    case torso = "\u{e825}"
    case tint = "\u{e824}"
    case thumbsDown = "\u{e823}"
    case time = "\u{e822}"
    case thumbsUp = "\u{e821}"
    case timeAlt = "\u{e820}"
    case thList = "\u{e81f}"
    case textHeight = "\u{e81e}"
    case th = "\u{e81d}"
    case soundcloud = "\u{e81c}"
    case star = "\u{e81b}"
    case tasks = "\u{e81a}"
    case tag = "\u{e819}"
    case stumbleupon = "\u{e818}"
    case thLarge = "\u{e817}"
    case textWidth = "\u{e816}"
    case spotify = "\u{e815}"
    case stepForward = "\u{e814}"
    case starAlt = "\u{e813}"
    case tags = "\u{e812}"
    case starEmpty = "\u{e811}"
    case stopAlt = "\u{e810}"
    case skype = "\u{e80f}"
    case stackoverflow = "\u{e80e}"
    case removeCircle = "\u{e80d}"
    case slideshare = "\u{e80c}"
    case stop = "\u{e80b}"
    case shoppingCart = "\u{e80a}"
    case qrcode = "\u{e809}"
    case resizeVertical = "\u{e808}"
    case smiley = "\u{e807}"
    case stepBackward = "\u{e806}"
    case speaker = "\u{e805}"
    case smileyAlt = "\u{e804}"
    case quoteRight = "\u{e803}"
    case searchAlt = "\u{e802}"
    case search = "\u{e801}"
    case shoppingCartSign = "\u{e800}"
    case playCircle = "\u{e7ff}"
    case rss = "\u{e7fe}"
    case signal = "\u{e7fd}"
    case pinterest = "\u{e7fc}"
    case share = "\u{e7fb}"
    case road = "\u{e7fa}"
    case shareAlt = "\u{e7f9}"
    case scissors = "\u{e7f8}"
    case repeatAlt = "\u{e7f7}"
    case screenshot = "\u{e7f6}"
    case screen = "\u{e7f5}"
    case plusSign = "\u{e7f4}"
    case screenAlt = "\u{e7f3}"
    case reddit = "\u{e7f2}"
    case reverseAlt = "\u{e7f1}"
    case returnKey = "\u{e7f0}"
    case resizeSmall = "\u{e7ef}"
    case `repeat` = "\u{e7ee}"
    case quotes = "\u{e7ed}"
    case resizeHorizontal = "\u{e7ec}"
    case resizeFull = "\u{e7eb}"
    case retweet = "\u{e7ea}"
    case redux = "\u{e7e9}"
    case removeSign = "\u{e7e8}"
    case plurk = "\u{e7e7}"
    case paperClipAlt = "\u{e7e6}"
    case podcast = "\u{e7e5}"
    case hourglass = "\u{e7e4}"
    case photo = "\u{e7e3}"
    case quoteAlt = "\u{e7e2}"
    case remove = "\u{e7e1}"
    case picasa = "\u{e7e0}"
    case random = "\u{e7df}"
    case refresh = "\u{e7de}"
    case phoneAlt = "\u{e7dd}"
    case plurkAlt = "\u{e7dc}"
    case record = "\u{e7db}"
    case lock = "\u{e7da}"
    case mic = "\u{e7d9}"
    case pencilAlt = "\u{e7d8}"
    case path = "\u{e7d7}"
    case leaf = "\u{e7d6}"
    case questionSign = "\u{e7d5}"
    case hearingImpaired = "\u{e7d4}"
    case opensource = "\u{e7d3}"
    case okCircle = "\u{e7d2}"
    case question = "\u{e7d1}"
    case quoteRightAlt = "\u{e7d0}"
    case male = "\u{e7cf}"
    case plus = "\u{e7ce}"
    case heartAlt = "\u{e7cd}"
    case puzzle = "\u{e7cc}"
    case print = "\u{e7cb}"
    case playAlt = "\u{e7ca}"
    case myspace = "\u{e7c9}"
    case list = "\u{e7c8}"
    case play = "\u{e7c7}"
    case paperClip = "\u{e7c6}"
    case plane = "\u{e7c5}"
    case photoAlt = "\u{e7c4}"
    case person = "\u{e7c3}"
    case picture = "\u{e7c2}"
    case lastfm = "\u{e7c1}"
    case network = "\u{e7c0}"
    case phone = "\u{e7bf}"
    case off = "\u{e7be}"
    case minus = "\u{e7bd}"
    case pauseAlt = "\u{e7bc}"
    case laptop = "\u{e7bb}"
    case pencil = "\u{e7ba}"
    case pause = "\u{e7b9}"
    case mapMarker = "\u{e7b8}"
    case music = "\u{e7b7}"
    case okSign = "\u{e7b6}"
    case magic = "\u{e7b5}"
    case move = "\u{e7b4}"
    case handLeft = "\u{e7b3}"
    case ok = "\u{e7b2}"
    case italic = "\u{e7b1}"
    case livejournal = "\u{e7b0}"
    case micAlt = "\u{e7af}"
    case minusSign = "\u{e7ae}"
    case home = "\u{e7ad}"
    case lockAlt = "\u{e7ac}"
    case idea = "\u{e7ab}"
    case linkedin = "\u{e7aa}"
    case indentRight = "\u{e7a9}"
    case magnet = "\u{e7a8}"
    case guidedog = "\u{e7a7}"
    case mapMarkerAlt = "\u{e7a6}"
    case listAlt = "\u{e7a5}"
    case link = "\u{e7a4}"
    case inboxBox = "\u{e7a3}"
    case laptopAlt = "\u{e7a2}"
    case inbox = "\u{e7a1}"
    case instagram = "\u{e7a0}"
    case iphoneHome = "\u{e79f}"
    case lines = "\u{e79e}"
    case ideaAlt = "\u{e79d}"
    case key = "\u{e79c}"
    case handRight = "\u{e79b}"
    case globeAlt = "\u{e79a}"
    case hdd = "\u{e799}"
    case infoCircle = "\u{e798}"
    case homeAlt = "\u{e797}"
    case inboxAlt = "\u{e796}"
    case gbp = "\u{e795}"
    case indentLeft = "\u{e794}"
    case group = "\u{e793}"
    case graphAlt = "\u{e792}"
    case heart = "\u{e791}"
    case handDown = "\u{e790}"
    case heartEmpty = "\u{e78f}"
    case headphones = "\u{e78e}"
    case handUp = "\u{e78d}"
    case folderOpen = "\u{e78c}"
    case googleplus = "\u{e78b}"
    case groupAlt = "\u{e78a}"
    case github = "\u{e789}"
    case graph = "\u{e788}"
    case globe = "\u{e787}"
    case friendfeedRect = "\u{e786}"
    case cogs = "\u{e785}"
    case forwardAlt = "\u{e784}"
    case githubText = "\u{e783}"
    case flag = "\u{e782}"
    case glasses = "\u{e781}"
    case glass = "\u{e780}"
    case fileNew = "\u{e77f}"
    case fileEditAlt = "\u{e77e}"
    case friendfeed = "\u{e77d}"
    case fastForward = "\u{e77c}"
    case foursquare = "\u{e77b}"
    case gift = "\u{e77a}"
    case fullscreen = "\u{e779}"
    case facebook = "\u{e778}"
    case fontsize = "\u{e777}"
    case fork = "\u{e776}"
    case folderSign = "\u{e775}"
    case forward = "\u{e774}"
    case exclamationSign = "\u{e773}"
    case flickr = "\u{e772}"
    case font = "\u{e771}"
    case folder = "\u{e770}"
    case download = "\u{e76f}"
    case eyeClose = "\u{e76e}"
    case errorAlt = "\u{e76d}"
    case fire = "\u{e76c}"
    case folderClose = "\u{e76b}"
    case flagAlt = "\u{e76a}"
    case child = "\u{e769}"
    case circleArrowRight = "\u{e768}"
    case eject = "\u{e767}"
    case filter = "\u{e766}"
    case fileNewAlt = "\u{e765}"
    case fileEdit = "\u{e764}"
    case film = "\u{e763}"
    case file = "\u{e762}"
    case deviantart = "\u{e761}"
    case error = "\u{e760}"
    case compassAlt = "\u{e75f}"
    case fastBackward = "\u{e75e}"
    case female = "\u{e75d}"
    case dribbble = "\u{e75c}"
    case fileAlt = "\u{e75b}"
    case bulb = "\u{e75a}"
    case digg = "\u{e759}"
    case facetimeVideo = "\u{e758}"
    case eyeOpen = "\u{e757}"
    case css = "\u{e756}"
    case eur = "\u{e755}"
    case bookmarkEmpty = "\u{e754}"
    case envelopeAlt = "\u{e753}"
    case edit = "\u{e752}"
    case envelope = "\u{e751}"
    case behance = "\u{e750}"
    case cloud = "\u{e74f}"
    case commentAlt = "\u{e74e}"
    case cogAlt = "\u{e74d}"
    case compass = "\u{e74c}"
    case downloadAlt = "\u{e74b}"
    case cc = "\u{e74a}"
    case delicious = "\u{e749}"
    case chevronLeft = "\u{e748}"
    case dashboard = "\u{e747}"
    case comment = "\u{e746}"
    case creditCard = "\u{e745}"
    case caretDown = "\u{e744}"
    case circleArrowUp = "\u{e743}"
    case cog = "\u{e742}"
    case chevronRight = "\u{e741}"
    case circleArrowLeft = "\u{e740}"
    case cloudAlt = "\u{e73f}"
    case checkEmpty = "\u{e73e}"
    case chevronDown = "\u{e73d}"
    case caretRight = "\u{e73c}"
    case circleArrowDown = "\u{e73b}"
    case chevronUp = "\u{e73a}"
    case bullhorn = "\u{e739}"
    case broom = "\u{e738}"
    case barcode = "\u{e737}"
    case blogger = "\u{e736}"
    case calendarSign = "\u{e735}"
    case calendar = "\u{e734}"
    case check = "\u{e733}"
    case caretUp = "\u{e732}"
    case certificate = "\u{e731}"
    case car = "\u{e730}"
    case camera = "\u{e72f}"
    case braille = "\u{e72e}"
    case caretLeft = "\u{e72d}"
    case alignRight = "\u{e72c}"
    case briefcase = "\u{e72b}"
    case bold = "\u{e72a}"
    case banCircle = "\u{e729}"
    case book = "\u{e728}"
    case brush = "\u{e727}"
    case blind = "\u{e726}"
    case alignJustify = "\u{e725}"
    case bookmark = "\u{e724}"
    case arrowRight = "\u{e723}"
    case asl = "\u{e722}"
    case arrowUp = "\u{e721}"
    case backward = "\u{e720}"
    case bell = "\u{e71f}"
    case arrowDown = "\u{e71e}"
    case asterisk = "\u{e71d}"
    case alignLeft = "\u{e71c}"
    case addressBookAlt = "\u{e71b}"
    case adjust = "\u{e71a}"
    case alignCenter = "\u{e719}"
    case arrowLeft = "\u{e718}"
    case adjustAlt = "\u{e717}"
    case adult = "\u{e716}"
    case addressBook = "\u{e715}"
}
