//
//  EFIconFontMetrizeIcons.swift
//  EFIconFont
//
//  Created by EyreFree on 2019/3/20.
//
//  Copyright (c) 2019 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation

public extension EFIconFont {

    static let metrizeIcons = EFIconFontMetrizeIcons.self
}

extension EFIconFontMetrizeIcons: EFIconFontCaseIterableProtocol {

    public static var name: String {
        return "metrizeicons"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontMetrizeIcons: String {
    case yen = "\u{eb8a}"
    case wind = "\u{eb89}"
    case threePoints = "\u{eb88}"
    case wireframeGlobe = "\u{eb87}"
    case textCenter = "\u{eb86}"
    case waves = "\u{eb85}"
    case userRemove = "\u{eb84}"
    case sos = "\u{eb83}"
    case wifi = "\u{eb82}"
    case viewport = "\u{eb81}"
    case upload = "\u{eb80}"
    case user = "\u{eb7f}"
    case uploadSelectionCircle = "\u{eb7e}"
    case threePointsTop = "\u{eb7d}"
    case userAdd = "\u{eb7c}"
    case viewportVideo = "\u{eb7b}"
    case userBan = "\u{eb7a}"
    case underline = "\u{eb79}"
    case textWidth = "\u{eb78}"
    case uploadSelection = "\u{eb77}"
    case textNormal = "\u{eb76}"
    case triplePoints = "\u{eb75}"
    case topBottom = "\u{eb74}"
    case textSizeReduce = "\u{eb73}"
    case textSizeUpper = "\u{eb72}"
    case threePointsBottom = "\u{eb71}"
    case telephone = "\u{eb70}"
    case sunshine = "\u{eb6f}"
    case textJustifyRight = "\u{eb6e}"
    case textJustifyLeft = "\u{eb6d}"
    case textParagraph = "\u{eb6c}"
    case textJustifyCenter = "\u{eb6b}"
    case textAlignRight = "\u{eb6a}"
    case socialWordpress = "\u{eb69}"
    case textBold = "\u{eb68}"
    case textHeight = "\u{eb67}"
    case sun = "\u{eb66}"
    case textAlignLeft = "\u{eb65}"
    case socialYoutube = "\u{eb64}"
    case socialLastFm = "\u{eb63}"
    case speed = "\u{eb62}"
    case stop = "\u{eb61}"
    case soundOn = "\u{eb60}"
    case socialVirb = "\u{eb5f}"
    case socialGooglePlus = "\u{eb5e}"
    case star = "\u{eb5d}"
    case socialYelp = "\u{eb5c}"
    case soundOff = "\u{eb5b}"
    case socialYahoo = "\u{eb5a}"
    case socialVimeo = "\u{eb59}"
    case socialZerply = "\u{eb58}"
    case socialGithub = "\u{eb57}"
    case socialTwitter = "\u{eb56}"
    case socialPinterest = "\u{eb55}"
    case socialPhotobucket = "\u{eb54}"
    case socialSoundcloud = "\u{eb53}"
    case socialSkype = "\u{eb52}"
    case socialBebo = "\u{eb51}"
    case socialViddler = "\u{eb50}"
    case socialPaypal = "\u{eb4f}"
    case socialStumbleupon = "\u{eb4e}"
    case socialTumblr = "\u{eb4d}"
    case socialQuora = "\u{eb4c}"
    case settings = "\u{eb4b}"
    case socialDribbble = "\u{eb4a}"
    case socialSharethis = "\u{eb49}"
    case socialLinkedin = "\u{eb48}"
    case socialEmail = "\u{eb47}"
    case socialMyspace = "\u{eb46}"
    case socialDigg = "\u{eb45}"
    case socialFlickr = "\u{eb44}"
    case socialEnvato = "\u{eb43}"
    case socialGrooveshark = "\u{eb42}"
    case socialFacebook = "\u{eb41}"
    case social500px = "\u{eb40}"
    case socialForrst = "\u{eb3f}"
    case socialBehance = "\u{eb3e}"
    case slidersVertical = "\u{eb3d}"
    case socialEvernote = "\u{eb3c}"
    case socialDeviantart = "\u{eb3b}"
    case signMale = "\u{eb3a}"
    case shield = "\u{eb39}"
    case socialBlogger = "\u{eb38}"
    case snow = "\u{eb37}"
    case podcast = "\u{eb36}"
    case selectSquare = "\u{eb35}"
    case selectCircle = "\u{eb34}"
    case socialAddthis = "\u{eb33}"
    case retweet = "\u{eb32}"
    case sliders = "\u{eb31}"
    case numberTwo = "\u{eb30}"
    case signFemale = "\u{eb2f}"
    case setting = "\u{eb2e}"
    case scale = "\u{eb2d}"
    case pigMoney = "\u{eb2c}"
    case locked = "\u{eb2b}"
    case previousFastStep = "\u{eb2a}"
    case rec = "\u{eb29}"
    case rules = "\u{eb28}"
    case reportComment = "\u{eb27}"
    case markerPoints = "\u{eb26}"
    case search = "\u{eb25}"
    case refresh = "\u{eb24}"
    case question = "\u{eb23}"
    case nextFastStep = "\u{eb22}"
    case pin = "\u{eb21}"
    case numberZero = "\u{eb20}"
    case pounds = "\u{eb1f}"
    case rss = "\u{eb1e}"
    case random = "\u{eb1d}"
    case lineThrough = "\u{eb1c}"
    case quote = "\u{eb1b}"
    case pause = "\u{eb1a}"
    case numberThree = "\u{eb19}"
    case prevStep = "\u{eb18}"
    case paperclipOblique = "\u{eb17}"
    case plus = "\u{eb16}"
    case play = "\u{eb15}"
    case optionsSettings = "\u{eb14}"
    case numberFour = "\u{eb13}"
    case pinMap = "\u{eb12}"
    case off = "\u{eb11}"
    case officine = "\u{eb10}"
    case paperclip = "\u{eb0f}"
    case officine2 = "\u{eb0e}"
    case numberFive = "\u{eb0d}"
    case numberSix = "\u{eb0c}"
    case numberNine = "\u{eb0b}"
    case numberOne = "\u{eb0a}"
    case nextStep = "\u{eb09}"
    case numberSeven = "\u{eb08}"
    case markerAdd = "\u{eb07}"
    case numberEight = "\u{eb06}"
    case minus = "\u{eb05}"
    case map = "\u{eb04}"
    case locationMaps = "\u{eb03}"
    case markerMinus = "\u{eb02}"
    case music = "\u{eb01}"
    case multiBorders = "\u{eb00}"
    case magnet = "\u{eaff}"
    case marker = "\u{eafe}"
    case maleSymbol = "\u{eafd}"
    case chartDown = "\u{eafc}"
    case loginLockRefresh = "\u{eafb}"
    case mailbox = "\u{eafa}"
    case linkUrl = "\u{eaf9}"
    case listSquare = "\u{eaf8}"
    case likeUpload = "\u{eaf7}"
    case magicWand = "\u{eaf6}"
    case mail = "\u{eaf5}"
    case location = "\u{eaf4}"
    case likeRemove = "\u{eaf3}"
    case info = "\u{eaf2}"
    case listCircle = "\u{eaf1}"
    case leaf = "\u{eaf0}"
    case likeClose = "\u{eaef}"
    case likeBan = "\u{eaee}"
    case limitDirections = "\u{eaed}"
    case likeAdd = "\u{eaec}"
    case likeDownload = "\u{eaeb}"
    case leftRight = "\u{eaea}"
    case hdd = "\u{eae9}"
    case landscape = "\u{eae8}"
    case italic = "\u{eae7}"
    case graphs = "\u{eae6}"
    case key = "\u{eae5}"
    case hddNet = "\u{eae4}"
    case homeWifi = "\u{eae3}"
    case idea = "\u{eae2}"
    case layers = "\u{eae1}"
    case heart = "\u{eae0}"
    case grids = "\u{eadf}"
    case exclamation = "\u{eade}"
    case hddRaid = "\u{eadd}"
    case eye = "\u{eadc}"
    case femaleSymbol = "\u{eadb}"
    case emailUpload = "\u{eada}"
    case gridBig = "\u{ead9}"
    case eject = "\u{ead8}"
    case forward = "\u{ead7}"
    case expand = "\u{ead6}"
    case expandDirections = "\u{ead5}"
    case fire = "\u{ead4}"
    case expandVertical = "\u{ead3}"
    case eyeDisabled = "\u{ead2}"
    case emailSpam = "\u{ead1}"
    case dotCircle = "\u{ead0}"
    case expandHorizontal = "\u{eacf}"
    case euro = "\u{eace}"
    case emailLuminosity = "\u{eacd}"
    case emailRemove = "\u{eacc}"
    case drops = "\u{eacb}"
    case emailDownload = "\u{eaca}"
    case emailAdd = "\u{eac9}"
    case downloadSelectionCircle = "\u{eac8}"
    case downloadSelection = "\u{eac7}"
    case drop = "\u{eac6}"
    case emailClose = "\u{eac5}"
    case download = "\u{eac4}"
    case copyDocument = "\u{eac3}"
    case copyPasteDocument = "\u{eac2}"
    case doubleDiamonds = "\u{eac1}"
    case comments = "\u{eac0}"
    case dollar = "\u{eabf}"
    case dotLine = "\u{eabe}"
    case document = "\u{eabd}"
    case coins = "\u{eabc}"
    case dotSquare = "\u{eabb}"
    case directions = "\u{eaba}"
    case documents = "\u{eab9}"
    case cross = "\u{eab8}"
    case documentFill = "\u{eab7}"
    case creditCard = "\u{eab6}"
    case contractVertical = "\u{eab5}"
    case cloudDownload = "\u{eab4}"
    case contractHorizontal = "\u{eab3}"
    case circles = "\u{eab2}"
    case chat = "\u{eab1}"
    case contractDirections = "\u{eab0}"
    case compass2 = "\u{eaaf}"
    case cloud = "\u{eaae}"
    case comment = "\u{eaad}"
    case compass = "\u{eaac}"
    case buttonEmail = "\u{eaab}"
    case cloudUpload = "\u{eaaa}"
    case clock = "\u{eaa9}"
    case cloudRemove = "\u{eaa8}"
    case cloudAdd = "\u{eaa7}"
    case check = "\u{eaa6}"
    case camera = "\u{eaa5}"
    case buttonQuestion = "\u{eaa4}"
    case buttonExclamation = "\u{eaa3}"
    case cdDvdRom = "\u{eaa2}"
    case buttonClose = "\u{eaa1}"
    case arrowCurveLeft = "\u{eaa0}"
    case buttonMinus = "\u{ea9f}"
    case arrowRight = "\u{ea9e}"
    case buttonCheck = "\u{ea9d}"
    case buttonAdd = "\u{ea9c}"
    case boxClose = "\u{ea9b}"
    case boxBlank = "\u{ea9a}"
    case brush = "\u{ea99}"
    case browserSizes = "\u{ea98}"
    case boxRemove = "\u{ea97}"
    case atom = "\u{ea96}"
    case boxAdd = "\u{ea95}"
    case bolt = "\u{ea94}"
    case bezier = "\u{ea93}"
    case banCircle = "\u{ea92}"
    case blockMenu = "\u{ea91}"
    case bars = "\u{ea90}"
    case blank = "\u{ea8f}"
    case axisRules = "\u{ea8e}"
    case backward = "\u{ea8d}"
    case bag = "\u{ea8c}"
    case arrowUp = "\u{ea8b}"
    case arrowUpThin = "\u{ea8a}"
    case arrowUpBoldRound = "\u{ea89}"
    case arrowUpLight = "\u{ea88}"
    case arrowUpBold = "\u{ea87}"
    case arrowUpBig = "\u{ea86}"
    case arrowRightThin = "\u{ea85}"
    case arrowRightLight = "\u{ea84}"
    case arrowMultiLineUp = "\u{ea83}"
    case arrowRightBoldRound = "\u{ea82}"
    case arrowMultiLineLeft = "\u{ea81}"
    case arrowRightBold = "\u{ea80}"
    case arrowRightBig = "\u{ea7f}"
    case arrowObliqueExpandDirections = "\u{ea7e}"
    case arrowObliqueExpand = "\u{ea7d}"
    case arrowObliqueContractDirections = "\u{ea7c}"
    case arrowObliqueContract = "\u{ea7b}"
    case arrowMultiLineDown = "\u{ea7a}"
    case arrowMultiLineRight = "\u{ea79}"
    case arrowLeftLight = "\u{ea78}"
    case arrowLeftBoldRound = "\u{ea77}"
    case arrowLeftThin = "\u{ea76}"
    case arrowDownThin = "\u{ea75}"
    case arrowFillRight = "\u{ea74}"
    case arrowLeft = "\u{ea73}"
    case arrowLeftBig = "\u{ea72}"
    case arrowFillLeft = "\u{ea71}"
    case arrowLeftBold = "\u{ea70}"
    case arrowFillUp = "\u{ea6f}"
    case arrowCycling = "\u{ea6e}"
    case arrowCycle = "\u{ea6d}"
    case arrowDownBold = "\u{ea6c}"
    case arrowDown = "\u{ea6b}"
    case arrowFillDown = "\u{ea6a}"
    case arrowDownLight = "\u{ea69}"
    case arrowDownBoldRound = "\u{ea68}"
    case arrowCurveRecycle = "\u{ea67}"
    case alarmClock = "\u{ea66}"
    case _3dCube = "\u{ea65}"
    case arrowDownBig = "\u{ea64}"
    case animalFootprint = "\u{ea63}"
    case arrowCurveRight = "\u{ea62}"
    case airPlane = "\u{ea61}"
    case adjust = "\u{ea60}"
}
