//
//  EFIconFontOpenIconic.swift
//  EFIconFont
//
//  Created by EyreFree on 2019/3/20.
//
//  Copyright (c) 2019 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation

public extension EFIconFont {

    public static let openIconic = EFIconFontOpenIconic.self
}

extension EFIconFontOpenIconic: EFIconFontCaseIterableProtocol {

    public static var name: String {
        return "openiconic"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontOpenIconic: String {
    case zoomOut = "\u{eb13}"
    case wrench = "\u{eb12}"
    case zoomIn = "\u{eb11}"
    case wifi = "\u{eb10}"
    case yen = "\u{eb0f}"
    case warning = "\u{eb0e}"
    case x = "\u{eb0d}"
    case volumeOff = "\u{eb0c}"
    case verticalAlignCenter = "\u{eb0b}"
    case volumeLow = "\u{eb0a}"
    case verticalAlignTop = "\u{eb09}"
    case volumeHigh = "\u{eb08}"
    case video = "\u{eb07}"
    case verticalAlignBottom = "\u{eb06}"
    case underline = "\u{eb05}"
    case trash = "\u{eb04}"
    case thumbUp = "\u{eb03}"
    case timer = "\u{eb02}"
    case transfer = "\u{eb01}"
    case text = "\u{eb00}"
    case tags = "\u{eaff}"
    case thumbDown = "\u{eafe}"
    case terminal = "\u{eafd}"
    case target = "\u{eafc}"
    case tablet = "\u{eafb}"
    case task = "\u{eafa}"
    case sun = "\u{eaf9}"
    case spreadsheet = "\u{eaf8}"
    case tag = "\u{eaf7}"
    case sortDescending = "\u{eaf6}"
    case star = "\u{eaf5}"
    case signal = "\u{eaf4}"
    case signpost = "\u{eaf3}"
    case shield = "\u{eaf2}"
    case sortAscending = "\u{eaf1}"
    case rss = "\u{eaf0}"
    case shareBoxed = "\u{eaef}"
    case share = "\u{eaee}"
    case rssAlt = "\u{eaed}"
    case script = "\u{eaec}"
    case rain = "\u{eaeb}"
    case resizeHeight = "\u{eaea}"
    case resizeWidth = "\u{eae9}"
    case resizeBoth = "\u{eae8}"
    case random = "\u{eae7}"
    case pulse = "\u{eae6}"
    case puzzlePiece = "\u{eae5}"
    case reload = "\u{eae4}"
    case powerStandby = "\u{eae3}"
    case questionMark = "\u{eae2}"
    case print = "\u{eae1}"
    case project = "\u{eae0}"
    case paperclip = "\u{eadf}"
    case loopSquare = "\u{eade}"
    case playCircle = "\u{eadd}"
    case pin = "\u{eadc}"
    case plus = "\u{eadb}"
    case person = "\u{eada}"
    case pieChart = "\u{ead9}"
    case phone = "\u{ead8}"
    case people = "\u{ead7}"
    case pencil = "\u{ead6}"
    case move = "\u{ead5}"
    case microphone = "\u{ead4}"
    case moon = "\u{ead3}"
    case monitor = "\u{ead2}"
    case musicalNote = "\u{ead1}"
    case minus = "\u{ead0}"
    case medicalCross = "\u{eacf}"
    case mediaStepBackward = "\u{eace}"
    case mediaStop = "\u{eacd}"
    case menu = "\u{eacc}"
    case mediaRecord = "\u{eacb}"
    case mediaStepForward = "\u{eaca}"
    case mediaSkipForward = "\u{eac9}"
    case mediaPlay = "\u{eac8}"
    case mediaSkipBackward = "\u{eac7}"
    case map = "\u{eac6}"
    case mapMarker = "\u{eac5}"
    case mediaPause = "\u{eac4}"
    case magnifyingGlass = "\u{eac3}"
    case lockLocked = "\u{eac2}"
    case loop = "\u{eac1}"
    case list = "\u{eac0}"
    case lockUnlocked = "\u{eabf}"
    case loopCircular = "\u{eabe}"
    case linkBroken = "\u{eabd}"
    case listRich = "\u{eabc}"
    case info = "\u{eabb}"
    case linkIntact = "\u{eaba}"
    case location = "\u{eab9}"
    case italic = "\u{eab8}"
    case lightbulb = "\u{eab7}"
    case layers = "\u{eab6}"
    case laptop = "\u{eab5}"
    case eyedropper = "\u{eab4}"
    case key = "\u{eab3}"
    case infinity = "\u{eab2}"
    case justifyCenter = "\u{eab1}"
    case justifyRight = "\u{eab0}"
    case home = "\u{eaaf}"
    case justifyLeft = "\u{eaae}"
    case headphones = "\u{eaad}"
    case image = "\u{eaac}"
    case gridThreeUp = "\u{eaab}"
    case inbox = "\u{eaaa}"
    case heart = "\u{eaa9}"
    case header = "\u{eaa8}"
    case gridTwoUp = "\u{eaa7}"
    case globe = "\u{eaa6}"
    case gridFourUp = "\u{eaa5}"
    case hardDrive = "\u{eaa4}"
    case fullscreenEnter = "\u{eaa3}"
    case graph = "\u{eaa2}"
    case fullscreenExit = "\u{eaa1}"
    case fork = "\u{eaa0}"
    case flash = "\u{ea9f}"
    case folder = "\u{ea9e}"
    case flag = "\u{ea9d}"
    case file = "\u{ea9c}"
    case fire = "\u{ea9b}"
    case externalLink = "\u{ea9a}"
    case eye = "\u{ea99}"
    case expandUp = "\u{ea98}"
    case euro = "\u{ea97}"
    case expandRight = "\u{ea96}"
    case expandLeft = "\u{ea95}"
    case expandDown = "\u{ea94}"
    case ellipses = "\u{ea93}"
    case excerpt = "\u{ea92}"
    case droplet = "\u{ea91}"
    case envelopeOpen = "\u{ea90}"
    case envelopeClosed = "\u{ea8f}"
    case elevator = "\u{ea8e}"
    case eject = "\u{ea8d}"
    case document = "\u{ea8c}"
    case delete = "\u{ea8b}"
    case doubleQuoteSansRight = "\u{ea8a}"
    case doubleQuoteSerifRight = "\u{ea89}"
    case doubleQuoteSerifLeft = "\u{ea88}"
    case doubleQuoteSansLeft = "\u{ea87}"
    case dollar = "\u{ea86}"
    case dial = "\u{ea85}"
    case dataTransferUpload = "\u{ea84}"
    case dataTransferDownload = "\u{ea83}"
    case crop = "\u{ea82}"
    case compass = "\u{ea81}"
    case creditCard = "\u{ea80}"
    case dashboard = "\u{ea7f}"
    case command = "\u{ea7e}"
    case contrast = "\u{ea7d}"
    case commentSquare = "\u{ea7c}"
    case copywriting = "\u{ea7b}"
    case caretBottom = "\u{ea7a}"
    case collapseUp = "\u{ea79}"
    case collapseLeft = "\u{ea78}"
    case collapseDown = "\u{ea77}"
    case collapseRight = "\u{ea76}"
    case cloudy = "\u{ea75}"
    case cloudDownload = "\u{ea74}"
    case code = "\u{ea73}"
    case cog = "\u{ea72}"
    case cloudUpload = "\u{ea71}"
    case cloud = "\u{ea70}"
    case clipboard = "\u{ea6f}"
    case circleX = "\u{ea6e}"
    case clock = "\u{ea6d}"
    case circleCheck = "\u{ea6c}"
    case chevronTop = "\u{ea6b}"
    case cameraSlr = "\u{ea6a}"
    case chevronRight = "\u{ea69}"
    case chevronLeft = "\u{ea68}"
    case chevronBottom = "\u{ea67}"
    case check = "\u{ea66}"
    case box = "\u{ea65}"
    case cart = "\u{ea64}"
    case chat = "\u{ea63}"
    case caretTop = "\u{ea62}"
    case caretRight = "\u{ea61}"
    case caretLeft = "\u{ea60}"
    case bug = "\u{ea5f}"
    case calendar = "\u{ea5e}"
    case calculator = "\u{ea5d}"
    case britishPound = "\u{ea5c}"
    case brush = "\u{ea5b}"
    case bullhorn = "\u{ea5a}"
    case briefcase = "\u{ea59}"
    case browser = "\u{ea58}"
    case book = "\u{ea57}"
    case bookmark = "\u{ea56}"
    case bluetooth = "\u{ea55}"
    case bold = "\u{ea54}"
    case bolt = "\u{ea53}"
    case beaker = "\u{ea52}"
    case batteryFull = "\u{ea51}"
    case basket = "\u{ea50}"
    case bell = "\u{ea4f}"
    case batteryEmpty = "\u{ea4e}"
    case barChart = "\u{ea4d}"
    case ban = "\u{ea4c}"
    case audio = "\u{ea4b}"
    case badge = "\u{ea4a}"
    case arrowThickLeft = "\u{ea49}"
    case arrowTop = "\u{ea48}"
    case arrowThickTop = "\u{ea47}"
    case audioSpectrum = "\u{ea46}"
    case arrowThickBottom = "\u{ea45}"
    case arrowThickRight = "\u{ea44}"
    case arrowLeft = "\u{ea43}"
    case aperture = "\u{ea42}"
    case arrowRight = "\u{ea41}"
    case arrowCircleTop = "\u{ea40}"
    case arrowCircleLeft = "\u{ea3f}"
    case arrowCircleBottom = "\u{ea3e}"
    case arrowCircleRight = "\u{ea3d}"
    case alignRight = "\u{ea3c}"
    case alignCenter = "\u{ea3b}"
    case actionUndo = "\u{ea3a}"
    case arrowBottom = "\u{ea39}"
    case accountLogout = "\u{ea38}"
    case alignLeft = "\u{ea37}"
    case accountLogin = "\u{ea36}"
    case actionRedo = "\u{ea35}"
}
